#!/bin/sh

usage () {
	echo "usage: $0"
	echo "  where <test_case_no> can be one of following:"
	echo "  0 -- traffic light system ST"
	echo "  1 -- light group controller UT"
	echo "  2 -- light controller UT"
	echo "  3 -- lane queue limited capacity UT"
	echo "  4 -- lane queue unlimited capacity UT"
	echo "  5 -- intersection queue UT"
	echo "  6 -- intersection controller UT"
	echo "  7 -- traffic collector UT"
	echo "  8 -- intersection coupled model UT"
	echo "  9 -- lane coupled model UT"
	echo " 10 -- traffic light coupled model UT"
	echo 	
	echo "  Examples:"
	echo "     run 0"
	echo "     run 10"
	echo 	
	return
}

SIMU=./simu

if  [ "$#" != "1" ]; then
	usage
	exit
fi

if [ ! -f ${SIMU} ]; then
	echo "Error: cannot find simulation program ${SIMU} !!"
	exit
fi

if [ ! -x ${SIMU} ]; then
	echo "Error: The smulation program ${SIMU} is not execuatable !!"
	exit
fi


if [ "$1" = "1" ]; then

	sh ./test_group_controller

elif [ "$1" = "2" ]; then

	sh ./test_light_controller

elif [ "$1" = "3" ]; then
  	
	sh ./test_lane_queue_limited

elif [ "$1" = "4" ]; then
  	
	sh ./test_lane_queue_unlimited

elif [ "$1" = "5" ]; then
  	
	sh ./test_intersection_queue

elif [ "$1" = "6" ]; then
  	
	sh ./test_intersection_controller

elif [ "$1" = "7" ]; then
  	
	sh ./test_traffic_collector

elif [ "$1" = "8" ]; then
  	
	sh ./test_intersection

elif [ "$1" = "9" ]; then
  	
	sh ./test_lane

elif [ "$1" = "10" ]; then
  	
	sh ./test_traffic_light

elif [ "$1" = "0" ]; then

	sh ./test_top

else
	usage
	exit
fi

